version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: dynamic_form_builder
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dynamic_form_builder"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./dynamic-form-builder
    container_name: nest_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: dynamic_form_builder
      PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./dynamic-form-app
    container_name: next_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
    depends_on:
      - backend

  seeder:
    build: 
      context: ./dynamic-form-builder
      dockerfile: Dockerfile.seed
    container_name: nest_seeder
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: dynamic_form_builder
    depends_on:
      backend:
        condition: service_healthy
    restart: "no"
    profiles:
      - seed

volumes:
  postgres_data: